name: CI Pipeline for React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code  
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Show Files and Directories Before Build
        run: ls -R

      - name: Build App
        run: npm run build

      - name: Show Files and Directories after Build
        run: ls -R